# Generated by Django 4.1 on 2023-03-05 05:50

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_tokenid_user_tokenuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "targetAddress",
                    models.CharField(
                        max_length=64,
                        validators=[
                            api.validators.validate_lower_case,
                            api.validators.is_address,
                        ],
                    ),
                ),
                ("targetToken", models.CharField(max_length=64)),
                ("context", models.CharField(max_length=200)),
                (
                    "issuer",
                    models.CharField(
                        max_length=50,
                        validators=[
                            api.validators.validate_lower_case,
                            api.validators.is_address,
                        ],
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("complete", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="user", name="dateofbirth", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="user", name="nameshingles", field=models.TextField(null=True),
        ),
    ]
