# Generated by Django 4.1 on 2023-03-05 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_credentialrequest_user_dateofbirth_user_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="credentialrequest", name="targetAddress",),
        migrations.RemoveField(model_name="credentialrequest", name="targetToken",),
        migrations.AddField(
            model_name="credentialrequest",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="credentialrequest",
            name="issuer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issuer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
