# Generated by Django 4.1 on 2023-03-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_credentialrequest_targetaddress_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="email",),
        migrations.RemoveField(model_name="user", name="first_name",),
        migrations.RemoveField(model_name="user", name="last_name",),
    ]
