# Generated by Django 4.1 on 2023-03-14 23:40

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_user_email_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="password",),
        migrations.RemoveField(model_name="user", name="tokenId",),
        migrations.RemoveField(model_name="user", name="tokenUID",),
        migrations.AlterField(
            model_name="user",
            name="publicAddress",
            field=models.CharField(
                max_length=64, unique=True, validators=[api.validators.is_address]
            ),
        ),
    ]
