# Generated by Django 4.1 on 2023-03-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_user_password_remove_user_tokenid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tokenId",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
