# Generated by Django 4.1 on 2023-03-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_user_tokenid"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifiableCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json", models.TextField()),
            ],
        ),
    ]
