# Generated by Django 4.1 on 2023-03-15 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_verifiablecredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifiablecredential",
            name="holder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
