# Generated by Django 4.1 on 2023-03-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_verifiablecredential_holder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tokenId",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
